"use strict";
const CFG={reload:7200,rotate:30,maxBars:14,colors:{involuntaria:"#f15357",voluntaria:"#347fe4","Sem.Info":"#7e91aa"}};
const S={b:[],e:[],i:[],p:[],m:[],view:"baixados",stockView:"terceiras",metaPage:0,left:30};
const views=["baixados","internalizados","metas","estoques","previsao"],F=new Intl.NumberFormat("pt-BR"),$=id=>document.getElementById(id),n=v=>Number(String(v??0).replace(",","."))||0,norm=v=>String(v??"").trim();
function pct(v){const x=parseFloat(norm(v).replace("%","").replace(",","."));return Number.isFinite(x)?x:0}
function dt(v){const m=norm(v).match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?new Date(+m[3],+m[2]-1,+m[1]):null}function latest(a,f){return a.map(x=>dt(x[f])).filter(Boolean).sort((a,b)=>b-a)[0]||null}function same(v,d){const x=dt(v);return x&&d&&+x===+d}function sameMonth(v,d){const x=dt(v);return x&&d&&x.getMonth()===d.getMonth()&&x.getFullYear()===d.getFullYear()}function show(d){return d?d.toLocaleDateString("pt-BR"):"Sem dados"}function sum(a){return a.reduce((t,r)=>t+n(r.Volume),0)}
function parse(t){t=t.replace(/^\uFEFF/,"");let rows=[],row=[],f="",q=false;for(let i=0;i<t.length;i++){let c=t[i],nx=t[i+1];if(c==='"'&&q&&nx==='"'){f+='"';i++}else if(c==='"')q=!q;else if(c===';'&&!q){row.push(f);f=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&nx==='\n')i++;row.push(f);if(row.some(Boolean))rows.push(row);row=[];f=""}else f+=c}if(f||row.length){row.push(f);rows.push(row)}const h=(rows.shift()||[]).map(norm);return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x,norm(r[i])])))}async function csv(u){const r=await fetch(u+"?v="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error(`${u}: HTTP ${r.status}`);return parse(await r.text())}
function group(a,label){const m=new Map();a.forEach(r=>{const k=norm(r[label])||"Sem.Info",raw=norm(r.Tipo_Desconexao).toLowerCase(),typ=raw==="voluntaria"?"voluntaria":raw==="involuntaria"?"involuntaria":"Sem.Info";if(!m.has(k))m.set(k,{label:k,involuntaria:0,voluntaria:0,"Sem.Info":0,total:0});const o=m.get(k),v=n(r.Volume);o[typ]+=v;o.total+=v});return[...m.values()].sort((a,b)=>b.total-a.total)}
function viewData(){
 if(S.view==="baixados"){const d=latest(S.b,"Data_Baixa");return{tag:"BAIXADOS",title:`Volume por agente — ${show(d)}`,rows:group(S.b.filter(r=>same(r.Data_Baixa,d)),"Armazem_Agrupado"),type:"bar"}}
 if(S.view==="internalizados"){const d=latest(S.i,"Data_Internalizacao");return{tag:"INTERNALIZADOS",title:`Volume por origem — ${show(d)}`,rows:group(S.i.filter(r=>same(r.Data_Internalizacao,d)),"Armazem_Agrupado_Origem"),type:"bar"}}
 if(S.view==="metas"){const rows=S.m.map(r=>({...r,ritmo:pct(r.Ritmo),meta:n(r.Meta_Mes),previsao:n(r.Previsao_Fechamento),falta:n(r.Falta_Coletar),estoque:n(r.Estoque_Agentes),internalizado:n(r.Internalizado_Mes),baixado:n(r.Baixado_Hoje),motoqueiros:n(r.Motoqueiros)})).sort((a,b)=>a.ritmo-b.ritmo||b.falta-a.falta);return{tag:"METAS TERCEIRAS",title:"Acompanhamento de metas por agente e UF",rows,type:"metas"}};
 if(S.view==="previsao"){const hoje=new Date();hoje.setHours(0,0,0,0);const rows=S.p.filter(r=>same(r.Data_Prev,hoje)).sort((a,b)=>norm(a.Equipe).localeCompare(norm(b.Equipe),"pt-BR"));return{tag:"PREVISÃO ENTREGA",title:`Entregas previstas para hoje — ${show(hoje)}`,rows,type:"forecast"}};
 if(S.stockView==="lojas")return{tag:"ESTOQUE D-1 — LOJAS",title:"Estoque consolidado por UF",rows:group(S.e.filter(r=>r.Tipo_Armazem==="ALARES LOJA"),"UF"),type:"uf"};
 return{tag:"ESTOQUE D-1 — TERCEIRAS",title:"Estoque por terceira",rows:group(S.e.filter(r=>r.Tipo_Armazem==="TERCEIROS COLETA"),"Armazem_Exibicao"),type:"third"}
}
function stack(r,labels,total,max){return["involuntaria","voluntaria","Sem.Info"].map(k=>{if(!r[k])return"";const rowPct=r[k]/r.total*100,allPct=r[k]/total*100,visible=r[k]/max*100>=7,txt=labels&&visible?`<b>${F.format(r[k])} <em>/</em> ${allPct.toFixed(1).replace(".",",")}%</b>`:"";return`<i class="seg" title="${k}: ${F.format(r[k])}" style="width:${rowPct}%;min-width:${rowPct<2?8:0}px;background:${CFG.colors[k]}">${txt}</i>`}).join("")}
function cards(rows){return rows.slice(0,13).map(r=>{const d=[["invol",r.involuntaria,"involuntaria"],["vol",r.voluntaria,"voluntaria"],["sem info",r["Sem.Info"],"Sem.Info"]].filter(x=>x[1]).map(([l,v,k])=>`<span><i style="background:${CFG.colors[k]}"></i>${l}: <b>${F.format(v)} / ${(v/r.total*100).toFixed(1).replace(".",",")}%</b></span>`).join("");return`<article class="stock-card"><div class="stock-head"><span title="${r.label}">${r.label}</span><strong>${F.format(r.total)}</strong></div><div class="stock-details">${d}</div></article>`}).join("")}
function ufTable(rows){return`<div class="table-wrap uf-table"><table><thead><tr><th>UF</th><th>Vol</th><th>Invol</th><th>Sem info</th><th>Total geral</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.label}</td><td>${F.format(r.voluntaria)}</td><td>${F.format(r.involuntaria)}</td><td>${F.format(r["Sem.Info"])}</td><td><b>${F.format(r.total)}</b></td></tr>`).join("")}</tbody><tfoot><tr><td>Total geral</td><td>${F.format(rows.reduce((t,r)=>t+r.voluntaria,0))}</td><td>${F.format(rows.reduce((t,r)=>t+r.involuntaria,0))}</td><td>${F.format(rows.reduce((t,r)=>t+r["Sem.Info"],0))}</td><td>${F.format(rows.reduce((t,r)=>t+r.total,0))}</td></tr></tfoot></table></div>`}
function metaColor(r){if(r>=100)return"#24c875";if(r>=80)return"#347fe4";if(r>=60)return"#f2b94b";return"#f15357"}
function metaResumo(rows){const meta=rows.reduce((t,r)=>t+r.meta,0),prev=rows.reduce((t,r)=>t+r.previsao,0),falta=rows.reduce((t,r)=>t+r.falta,0),ritmo=meta?prev/meta*100:0;return`<div class="meta-kpis"><article><span>Meta do mês</span><strong>${F.format(meta)}</strong></article><article><span>Previsão fechamento</span><strong>${F.format(prev)}</strong></article><article><span>Ritmo geral</span><strong>${ritmo.toFixed(1).replace(".",",")}%</strong></article><article><span>Falta coletar</span><strong>${F.format(falta)}</strong></article></div>`}
function metaCards(rows){const pageSize=8,totalPages=Math.max(1,Math.ceil(rows.length/pageSize)),page=Math.min(S.metaPage,totalPages-1),start=page*pageSize,items=rows.slice(start,start+pageSize);return`<div class="meta-page-head"><span>Prioridade: menor ritmo primeiro</span><b>Página ${page+1}/${totalPages}</b></div><div class="meta-list">${items.map((r,i)=>{const cor=metaColor(r.ritmo),largura=Math.min(r.ritmo,100),moto=r.motoqueiros>0?F.format(r.motoqueiros):"—";return`<article class="meta-row"><div class="meta-rank">${start+i+1}</div><div class="meta-content"><div class="meta-title"><strong>${norm(r.UF)} | ${norm(r.Agente)}</strong><span class="owner">${norm(r.Responsavel)||"Sem responsável"}</span></div><div class="meta-progress"><i style="width:${largura}%;background:${cor}"></i><b>${r.ritmo.toFixed(1).replace(".",",")}%</b></div><div class="meta-details"><span>Meta <b>${F.format(r.meta)}</b></span><span>Prev. <b>${F.format(r.previsao)}</b></span><span>Falta <b>${F.format(r.falta)}</b></span><span>Estoque <b>${F.format(r.estoque)}</b></span><span>Int. mês <b>${F.format(r.internalizado)}</b></span><span>Motoq. <b>${moto}</b></span></div></div></article>`}).join("")}</div>`}
function metasView(rows){if(!rows.length)return`<div class="forecast-empty"><strong>Base de metas sem registros</strong><span>Verifique data/metas_terceiras.csv</span></div>`;return`<div class="metas-view">${metaResumo(rows)}${metaCards(rows)}</div>`}
function forecastTable(rows){if(!rows.length)return`<div class="forecast-empty"><strong>Nenhuma entrega prevista para hoje</strong><span>${show(new Date())}</span></div>`;return`<div class="forecast-wrap"><table><thead><tr><th>Armazém / Equipe</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${norm(r.Equipe)||"Sem informação"}</td></tr>`).join("")}</tbody></table></div>`}
function stockSwitch(){return`<div class="stock-switch"><button class="${S.stockView==='terceiras'?'active':''}" data-stock="terceiras">Terceiras</button><button class="${S.stockView==='lojas'?'active':''}" data-stock="lojas">Lojas por UF</button></div>`}
function setupNav(){const nav=document.querySelector("nav");if(!nav)return;nav.innerHTML=`<button data-view="baixados">Baixados</button><button data-view="internalizados">Internalizado</button><button data-view="metas">Metas Terceiras</button><button data-view="estoques">Estoques</button><button data-view="previsao">Previsão Entrega</button><span>Alternância automática: <b id="contadorVisao">30s</b></span>`;nav.querySelectorAll("button").forEach(b=>b.onclick=()=>setView(b.dataset.view))}
function render(){const v=viewData(),all=v.rows,rows=all.slice(0,CFG.maxBars),max=Math.max(...rows.map(r=>r.total),1),total=all.reduce((t,r)=>t+r.total,0);$("rotuloGrafico").textContent=v.tag;$("tituloGrafico").textContent=v.title;$("nomeVisao").textContent=v.title;document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===S.view));$("legendaGrafico").innerHTML=["pending","metas","forecast"].includes(v.type)?"":Object.entries(CFG.colors).map(([k,c])=>`<span><i style="background:${c}"></i>${k}</span>`).join("");const g=$("graficoPrincipal");if(v.type==="metas"){g.className="metas-container";g.innerHTML=metasView(all)}else if(v.type==="forecast"){g.className="forecast-view";g.innerHTML=forecastTable(all)}else if(v.type==="pending"){g.className="pending-view";g.innerHTML=`<div><strong>${v.tag}</strong><p>${v.message}</p></div>`}else if(v.type==="third"){g.className="stock-area";g.innerHTML=stockSwitch()+`<div class="third-grid">${cards(all)}</div>`;g.querySelectorAll("[data-stock]").forEach(b=>b.onclick=()=>{S.stockView=b.dataset.stock;render()})}else if(v.type==="uf"){g.className="stock-area";g.innerHTML=stockSwitch()+ufTable(all);g.querySelectorAll("[data-stock]").forEach(b=>b.onclick=()=>{S.stockView=b.dataset.stock;render()})}else{g.className="bar-chart";g.innerHTML=rows.map(r=>`<div class="bar-row"><span class="blabel">${r.label}</span><div class="btrack"><div class="bfill" style="width:${r.total/max*100}%">${stack(r,true,total,max)}</div></div><strong>${F.format(r.total)}</strong></div>`).join("")}
 const showSide=v.type!=="pending"&&v.type!=="forecast"&&v.type!=="metas";document.querySelector(".grid aside").style.visibility=showSide?"visible":"hidden";if(!showSide)return;const totals=all.reduce((a,r)=>{["involuntaria","voluntaria","Sem.Info"].forEach(k=>a[k]+=r[k]);a.total+=r.total;return a},{involuntaria:0,voluntaria:0,"Sem.Info":0,total:0});$("tituloComposicao").textContent="Tipo de desconexão";$("composicao").innerHTML=["involuntaria","voluntaria","Sem.Info"].map(k=>`<div class="comp"><span>${k}<b>${F.format(totals[k])}</b></span><div><i style="width:${totals.total?totals[k]/totals.total*100:0}%;background:${CFG.colors[k]}"></i></div></div>`).join("");$("totalVisao").textContent=F.format(totals.total);$("maiorAgente").textContent=all[0]?.label||"—";$("maiorAgenteValor").textContent=F.format(all[0]?.total||0)+" equipamentos";$("ticker").innerHTML=all.slice(0,10).map((r,i)=>`<span><b>${i+1}º ${r.label}</b> | ${F.format(r.total)}</span>`).join("")}
function kpis(){const db=latest(S.b,"Data_Baixa"),di=latest(S.i,"Data_Internalizacao"),third=S.e.filter(r=>r.Tipo_Armazem==="TERCEIROS COLETA");$("kpiBaixadosHoje").textContent=F.format(sum(S.b.filter(r=>same(r.Data_Baixa,db))));$("kpiBaixadosMes").textContent=F.format(sum(S.b.filter(r=>sameMonth(r.Data_Baixa,db))));$("subBaixadosHoje").textContent=show(db);$("kpiEstoque").textContent=F.format(sum(third));const stockCard=$("kpiEstoque")?.closest("article");if(stockCard){stockCard.querySelector("span").textContent="Estoque D-1 — Terceiras";stockCard.querySelector("small").textContent="Somente terceiros de coleta"}$("kpiInternalizadosHoje").textContent=F.format(sum(S.i.filter(r=>same(r.Data_Internalizacao,di))));$("kpiInternalizadosMes").textContent=F.format(sum(S.i.filter(r=>sameMonth(r.Data_Internalizacao,di))));$("subInternalizadosHoje").textContent=show(di);$("dataBase").textContent=show([db,di].filter(Boolean).sort((a,b)=>b-a)[0])}
function setView(v){S.view=v;S.left=CFG.rotate;if(v==="estoques")S.stockView="terceiras";if(v==="metas")S.metaPage=0;render()}function timers(){setInterval(()=>$("relogio").textContent=new Date().toLocaleString("pt-BR"),1000);let r=CFG.reload;setInterval(()=>{r--;$("contadorRefresh").textContent=[Math.floor(r/3600),Math.floor(r%3600/60),r%60].map(x=>String(x).padStart(2,"0")).join(":");if(r<=0)location.reload()},1000);setInterval(()=>{S.left--;const c=$("contadorVisao");if(c)c.textContent=S.left+"s";if(S.view==="estoques"&&S.left===15){S.stockView="lojas";render()}if(S.view==="metas"&&S.left===15){S.metaPage=1;render()}if(S.left<=0)setView(views[(views.indexOf(S.view)+1)%views.length])},1000)}
async function init(){setupNav();timers();try{[S.b,S.e,S.i,S.p,S.m]=await Promise.all([csv("data/baixados.csv"),csv("data/estoque.csv"),csv("data/internalizados.csv"),csv("data/previsao_entrega.csv"),csv("data/metas_terceiras.csv")]);kpis();render();$("statusBase").className="status ok";$("statusBase").textContent="ATUALIZADO"}catch(e){$("statusBase").textContent="ERRO NA BASE";$("erroGlobal").hidden=false;$("erroGlobal").textContent=e.message}}init();
