"use strict";
const CFG={reload:1800,rotate:30,maxBars:14,colors:{involuntaria:"#f15357",voluntaria:"#347fe4","Sem.Info":"#7e91aa"}};
const S={b:[],e:[],i:[],p:[],m:[],dataUpdatedAt:null,view:"baixados",stockView:"terceiras",metaPage:0,rhythmPage:0,highlightIndex:0,left:30};
const views=["baixados","internalizados","metas","ritmo","estoques","previsao"],F=new Intl.NumberFormat("pt-BR"),$=id=>document.getElementById(id),n=v=>Number(String(v??0).replace(",","."))||0,norm=v=>String(v??"").trim();
function pct(v){const x=parseFloat(norm(v).replace("%","").replace(",","."));return Number.isFinite(x)?x:0}
function dt(v){const m=norm(v).match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?new Date(+m[3],+m[2]-1,+m[1]):null}function latest(a,f){return a.map(x=>dt(x[f])).filter(Boolean).sort((a,b)=>b-a)[0]||null}function same(v,d){const x=dt(v);return x&&d&&+x===+d}function sameMonth(v,d){const x=dt(v);return x&&d&&x.getMonth()===d.getMonth()&&x.getFullYear()===d.getFullYear()}function show(d){return d?d.toLocaleDateString("pt-BR"):"Sem dados"}function sum(a){return a.reduce((t,r)=>t+n(r.Volume),0)}
function parse(t){t=t.replace(/^\uFEFF/,"");let rows=[],row=[],f="",q=false;for(let i=0;i<t.length;i++){let c=t[i],nx=t[i+1];if(c==='"'&&q&&nx==='"'){f+='"';i++}else if(c==='"')q=!q;else if(c===';'&&!q){row.push(f);f=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&nx==='\n')i++;row.push(f);if(row.some(Boolean))rows.push(row);row=[];f=""}else f+=c}if(f||row.length){row.push(f);rows.push(row)}const h=(rows.shift()||[]).map(norm);return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x,norm(r[i])])))}async function csv(u){const r=await fetch(u+"?v="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error(`${u}: HTTP ${r.status}`);const last=r.headers.get("last-modified"),updatedAt=last?new Date(last):null;return{rows:parse(await r.text()),updatedAt:updatedAt&&Number.isFinite(+updatedAt)?updatedAt:null}}
function group(a,label){const m=new Map();a.forEach(r=>{const k=norm(r[label])||"Sem.Info",raw=norm(r.Tipo_Desconexao).toLowerCase(),typ=raw==="voluntaria"?"voluntaria":raw==="involuntaria"?"involuntaria":"Sem.Info";if(!m.has(k))m.set(k,{label:k,involuntaria:0,voluntaria:0,"Sem.Info":0,total:0});const o=m.get(k),v=n(r.Volume);o[typ]+=v;o.total+=v});return[...m.values()].sort((a,b)=>b.total-a.total)}
function viewData(){
 if(S.view==="baixados"){const d=latest(S.b,"Data_Baixa");return{tag:"BAIXADOS",title:`Volume por agente — ${show(d)}`,rows:group(S.b.filter(r=>same(r.Data_Baixa,d)),"Armazem_Agrupado"),type:"bar"}}
 if(S.view==="internalizados"){const d=latest(S.i,"Data_Internalizacao");return{tag:"INTERNALIZADOS",title:`Volume por origem — ${show(d)}`,rows:group(S.i.filter(r=>same(r.Data_Internalizacao,d)),"Armazem_Agrupado_Origem"),type:"bar"}}
 if(S.view==="metas"){const rows=S.m.map(r=>({...r,ritmo:pct(r.Ritmo),meta:n(r.Meta_Mes),previsao:n(r.Previsao_Fechamento),falta:n(r.Falta_Coletar),estoque:n(r.Estoque_Agentes),internalizado:n(r.Internalizado_Mes),baixado:n(r.Baixado_Hoje),motoqueiros:n(r.Motoqueiros)})).sort((a,b)=>a.ritmo-b.ritmo||b.falta-a.falta);return{tag:"METAS TERCEIRAS",title:"Acompanhamento de metas por agente e UF",rows,type:"metas"}};
 if(S.view==="ritmo"){const rows=ritmoRows();return{tag:"RITMO DO MÊS",title:"Ritmo atual das terceiras",rows,type:"rhythm"}};
 if(S.view==="previsao"){const hoje=new Date();hoje.setHours(0,0,0,0);const rows=S.p.filter(r=>same(r.Data_Prev,hoje)).sort((a,b)=>norm(a.Equipe).localeCompare(norm(b.Equipe),"pt-BR"));return{tag:"PREVISÃO ENTREGA",title:`Entregas previstas para hoje — ${show(hoje)}`,rows,type:"forecast"}};
 if(S.stockView==="lojas")return{tag:"ESTOQUE D-1 — LOJAS",title:"Estoque consolidado por UF",rows:group(S.e.filter(r=>r.Tipo_Armazem==="ALARES LOJA"),"UF"),type:"uf"};
 return{tag:"ESTOQUE D-1 — TERCEIRAS",title:"Estoque por terceira",rows:group(S.e.filter(r=>r.Tipo_Armazem==="TERCEIROS COLETA"),"Armazem_Exibicao"),type:"third"}
}
function stack(r,labels,total,max){return["involuntaria","voluntaria","Sem.Info"].map(k=>{if(!r[k])return"";const rowPct=r[k]/r.total*100,txt=labels?`<b>${F.format(r[k])}</b>`:"";return`<i class="seg ${labels?"seg-volume":""}" title="${k}: ${F.format(r[k])}" style="width:${rowPct}%;min-width:${labels?22:rowPct<2?8:0}px;background:${CFG.colors[k]}">${txt}</i>`}).join("")}
function cards(rows){return rows.slice(0,13).map(r=>{const d=[["invol",r.involuntaria,"involuntaria"],["vol",r.voluntaria,"voluntaria"],["sem info",r["Sem.Info"],"Sem.Info"]].filter(x=>x[1]).map(([l,v,k])=>`<span><i style="background:${CFG.colors[k]}"></i>${l}: <b>${F.format(v)} / ${(v/r.total*100).toFixed(1).replace(".",",")}%</b></span>`).join("");return`<article class="stock-card"><div class="stock-head"><span title="${r.label}">${r.label}</span><strong>${F.format(r.total)}</strong></div><div class="stock-details">${d}</div></article>`}).join("")}
function ufTable(rows){return`<div class="table-wrap uf-table"><table><thead><tr><th>UF</th><th>Vol</th><th>Invol</th><th>Sem info</th><th>Total geral</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.label}</td><td>${F.format(r.voluntaria)}</td><td>${F.format(r.involuntaria)}</td><td>${F.format(r["Sem.Info"])}</td><td><b>${F.format(r.total)}</b></td></tr>`).join("")}</tbody><tfoot><tr><td>Total geral</td><td>${F.format(rows.reduce((t,r)=>t+r.voluntaria,0))}</td><td>${F.format(rows.reduce((t,r)=>t+r.involuntaria,0))}</td><td>${F.format(rows.reduce((t,r)=>t+r["Sem.Info"],0))}</td><td>${F.format(rows.reduce((t,r)=>t+r.total,0))}</td></tr></tfoot></table></div>`}
function metaColor(r){if(r>=100)return"#24c875";if(r>=80)return"#347fe4";if(r>=60)return"#f2b94b";return"#f15357"}
function metaResumo(rows){const meta=rows.reduce((t,r)=>t+r.meta,0),prev=rows.reduce((t,r)=>t+r.previsao,0),falta=rows.reduce((t,r)=>t+r.falta,0),ritmo=meta?prev/meta*100:0;return`<div class="meta-kpis"><article><span>Meta do mês</span><strong>${F.format(meta)}</strong></article><article><span>Previsão fechamento</span><strong>${F.format(prev)}</strong></article><article><span>Ritmo geral</span><strong>${ritmo.toFixed(1).replace(".",",")}%</strong></article><article><span>Falta coletar</span><strong>${F.format(falta)}</strong></article></div>`}
function metaCards(rows){const pageSize=8,totalPages=Math.max(1,Math.ceil(rows.length/pageSize)),page=Math.min(S.metaPage,totalPages-1),start=page*pageSize,items=rows.slice(start,start+pageSize),prevDisabled=page===0?"disabled":"",nextDisabled=page>=totalPages-1?"disabled":"";return`<div class="meta-page-head"><span>Prioridade: menor ritmo primeiro</span><div class="meta-pagination"><button type="button" data-meta-page="prev" ${prevDisabled} aria-label="Página anterior">‹</button><b>Página ${page+1}/${totalPages}</b><button type="button" data-meta-page="next" ${nextDisabled} aria-label="Próxima página">›</button></div></div><div class="meta-list">${items.map((r,i)=>{const cor=metaColor(r.ritmo),largura=Math.min(r.ritmo,100),moto=r.motoqueiros>0?F.format(r.motoqueiros):"—";return`<article class="meta-row"><div class="meta-rank">${start+i+1}</div><div class="meta-content"><div class="meta-title"><strong>${norm(r.UF)} | ${norm(r.Agente)}</strong><span class="owner">${norm(r.Responsavel)||"Sem responsável"}</span></div><div class="meta-progress"><i style="width:${largura}%;background:${cor}"></i><b>${r.ritmo.toFixed(1).replace(".",",")}%</b></div><div class="meta-details meta-details-ordered"><span>Meta <b>${F.format(r.meta)}</b></span><span class="detail-today">Baix. hoje <b>${F.format(r.baixado)}</b></span><span class="detail-month">Int. mês <b>${F.format(r.internalizado)}</b></span><span class="detail-stock">Estoque <b>${F.format(r.estoque)}</b></span><span>Prev. fech. <b>${F.format(r.previsao)}</b></span><span class="detail-gap">Falta <b>${F.format(r.falta)}</b></span><span>Motoq. <b>${moto}</b></span></div></div></article>`}).join("")}</div>`}
function metasView(rows){if(!rows.length)return`<div class="forecast-empty"><strong>Base de metas sem registros</strong><span>Verifique data/metas_terceiras.csv</span></div>`;return`<div class="metas-view">${metaResumo(rows)}${metaCards(rows)}</div>`}
function f1(v){return Number(v||0).toLocaleString("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:1})}
function ritmoStatus(v){if(v>=100)return{label:"NO RITMO",className:"ontrack",color:"#24c875"};if(v>=80)return{label:"ATENÇÃO",className:"attention",color:"#f2b94b"};return{label:"AÇÃO NECESSÁRIA",className:"risk",color:"#f15357"}}
function ritmoRows(){
  return S.m.map(r=>({
    ...r,
    ritmo:pct(r.Ritmo),
    diasMes:n(r.Dias_Uteis_Mes),
    diasAtual:n(r.Dias_Uteis_Atual),
    diasRestantes:n(r.Dias_Uteis_Restantes)||Math.max(0,n(r.Dias_Uteis_Mes)-n(r.Dias_Uteis_Atual)),
    mes:norm(r.Mes_Atual)
  })).filter(r=>r.Agente).sort((a,b)=>b.ritmo-a.ritmo||norm(a.Agente).localeCompare(norm(b.Agente),"pt-BR"))
}
function ritmoResumo(rows){
  const first=rows[0]||{};
  return`<div class="rhythm-period"><span>${first.mes||"Mês não informado"}</span><b>${f1(first.diasAtual)} de ${f1(first.diasMes)} dias úteis transcorridos</b></div><div class="rhythm-kpis rhythm-kpis-calendar"><article><span>Dias úteis do mês</span><strong>${f1(first.diasMes)}</strong></article><article><span>Dias úteis transcorridos</span><strong>${f1(first.diasAtual)}</strong></article><article><span>Dias úteis restantes</span><strong>${f1(first.diasRestantes)}</strong></article></div>`
}
function ritmoCards(rows){
  const pageSize=8,totalPages=Math.max(1,Math.ceil(rows.length/pageSize)),page=Math.min(S.rhythmPage,totalPages-1),start=page*pageSize,items=rows.slice(start,start+pageSize),prevDisabled=page===0?"disabled":"",nextDisabled=page>=totalPages-1?"disabled":"";
  return`<div class="rhythm-page-head"><span>Maior ritmo primeiro</span><div class="rhythm-pagination"><button type="button" data-rhythm-page="prev" ${prevDisabled} aria-label="Página anterior">‹</button><b>Página ${page+1}/${totalPages}</b><button type="button" data-rhythm-page="next" ${nextDisabled} aria-label="Próxima página">›</button></div></div><div class="rhythm-table-wrap"><table class="rhythm-table rhythm-table-simple"><thead><tr><th>Terceira</th><th>Ritmo</th><th>Responsável</th></tr></thead><tbody>${items.map(r=>{const cor=metaColor(r.ritmo);return`<tr><td class="rhythm-agent"><strong>${norm(r.UF)} | ${norm(r.Agente)}</strong></td><td class="rhythm-percent"><div class="rhythm-percent-value"><b style="color:${cor}">${f1(r.ritmo)}%</b></div><span class="rhythm-percent-track"><i style="width:${Math.min(Math.max(r.ritmo,0),100)}%;background:${cor}"></i></span></td><td>${norm(r.Responsavel)||"Sem responsável"}</td></tr>`}).join("")}</tbody></table></div>`
}
function ritmoView(rows){if(!rows.length)return`<div class="forecast-empty"><strong>Dados de ritmo indisponíveis</strong><span>Inclua os campos de dias úteis em metas_terceiras.csv</span></div>`;const valid=rows.some(r=>r.diasMes>0);if(!valid)return`<div class="forecast-empty"><strong>Calendário operacional não informado</strong><span>Preencha Mes_Atual, Dias_Uteis_Mes, Dias_Uteis_Atual e Dias_Uteis_Restantes</span></div>`;return`<div class="rhythm-view">${ritmoResumo(rows)}${ritmoCards(rows)}</div>`}

function performanceRows(){return S.m.map(r=>({...r,ritmo:pct(r.Ritmo),meta:n(r.Meta_Mes),previsao:n(r.Previsao_Fechamento),falta:n(r.Falta_Coletar)})).filter(r=>r.Agente).sort((a,b)=>b.ritmo-a.ritmo)}
function highlightStatus(ritmo){if(ritmo>=80)return{label:ritmo>=100?"META ATINGIDA":"BOM RITMO",color:"#24c875",className:"good"};if(ritmo>=60)return{label:"ATENÇÃO",color:"#f2b94b",className:"warning"};return{label:"PRIORIDADE",color:"#f15357",className:"critical"}}
function buildHighlights(){
  const rows=performanceRows();
  if(!rows.length)return[];
  const groups=[
    {label:"BOM RITMO",color:"#24c875",className:"good",duration:40,rows:rows.filter(r=>r.ritmo>=80)},
    {label:"ATENÇÃO",color:"#f2b94b",className:"warning",duration:25,rows:rows.filter(r=>r.ritmo>=60&&r.ritmo<80)},
    {label:"PRIORIDADE",color:"#f15357",className:"critical",duration:45,rows:rows.filter(r=>r.ritmo<60)}
  ];
  return groups.filter(g=>g.rows.length).map(g=>({
    label:g.label,
    color:g.color,
    className:g.className,
    duration:g.duration,
    html:g.rows.map(r=>`<span class="highlight-agent"><small>${norm(r.UF)}</small><span>${norm(r.Agente)}</span><strong>${r.ritmo.toFixed(1).replace(".",",")}%</strong></span>`).join('<i class="highlight-separator"></i>')
  }));
}
function showHighlight(){const items=buildHighlights(),ticker=$("ticker");if(!ticker)return 25;if(!items.length){ticker.innerHTML='<span class="highlight-message"><b class="highlight-status">METAS TERCEIRAS</b><span>Sem dados de performance disponíveis</span></span>';return 25}const item=items[S.highlightIndex%items.length];ticker.className=`highlight-ticker ${item.className}`;ticker.style.setProperty("--highlight-duration",`${item.duration}s`);ticker.innerHTML=`<span class="highlight-message"><b class="highlight-status"><i style="background:${item.color}"></i>${item.label}</b><span class="highlight-agents">${item.html}</span></span>`;S.highlightIndex=(S.highlightIndex+1)%items.length;return item.duration}
function startHighlights(){const next=()=>{const duration=showHighlight();setTimeout(next,duration*1000)};next()}
function forecastTable(rows){if(!rows.length)return`<div class="forecast-empty"><strong>Nenhuma entrega prevista para hoje</strong><span>${show(new Date())}</span></div>`;return`<div class="forecast-wrap"><table><thead><tr><th>Armazém / Equipe</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${norm(r.Equipe)||"Sem informação"}</td></tr>`).join("")}</tbody></table></div>`}
function stockSwitch(){return`<div class="stock-switch"><button class="${S.stockView==='terceiras'?'active':''}" data-stock="terceiras">Terceiras</button><button class="${S.stockView==='lojas'?'active':''}" data-stock="lojas">Lojas por UF</button></div>`}
function setupResponsiveViewport(){let viewport=document.querySelector('meta[name="viewport"]');if(!viewport){viewport=document.createElement("meta");viewport.name="viewport";document.head.appendChild(viewport)}viewport.content="width=device-width, initial-scale=1, viewport-fit=cover"}
function setupHeaderUpdate(){const dataBase=$("dataBase"),dataBlock=dataBase?.closest("span");if(dataBlock)dataBlock.style.display="none";const status=$("statusBase");if(!status)return;if(S.dataUpdatedAt){status.textContent=`Atualizado ${S.dataUpdatedAt.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}`;status.title=`Última alteração detectada nos arquivos da pasta data: ${S.dataUpdatedAt.toLocaleString("pt-BR")}`}else{status.textContent="Atualização não informada";status.title="O servidor não forneceu a data de alteração dos arquivos"}}
function setupBrand(){const header=document.querySelector("header"),titleBlock=header?.firstElementChild;if(!titleBlock||titleBlock.querySelector(".alares-logo"))return;titleBlock.classList.add("brand-block");const logo=document.createElement("img");logo.src="assets/logo-alares.png";logo.alt="Alares";logo.className="alares-logo";const texts=document.createElement("div");texts.className="brand-text";while(titleBlock.firstChild)texts.appendChild(titleBlock.firstChild);titleBlock.appendChild(logo);titleBlock.appendChild(texts)}
function setupNav(){const nav=document.querySelector("nav");if(!nav)return;nav.innerHTML=`<button data-view="baixados">Baixados</button><button data-view="internalizados">Internalizado</button><button data-view="metas">Metas Terceiras</button><button data-view="ritmo">Ritmo do Mês</button><button data-view="estoques">Estoques</button><button data-view="previsao">Previsão Entrega</button><span class="view-timer"><span class="view-timer-label">Próxima visão em <b id="contadorVisao">30s</b></span><span class="view-progress" aria-hidden="true"><i id="barraVisao"></i></span></span>`;nav.querySelectorAll("button").forEach(b=>b.onclick=()=>setView(b.dataset.view))}
function render(){const v=viewData(),all=v.rows,rows=all.slice(0,CFG.maxBars),max=Math.max(...rows.map(r=>r.total),1),total=all.reduce((t,r)=>t+r.total,0);$("rotuloGrafico").textContent=v.tag;$("tituloGrafico").textContent=v.title;$("nomeVisao").textContent=v.title;document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===S.view));$("legendaGrafico").innerHTML=["pending","metas","rhythm","forecast"].includes(v.type)?"":Object.entries(CFG.colors).map(([k,c])=>`<span><i style="background:${c}"></i>${k}</span>`).join("");const g=$("graficoPrincipal");if(v.type==="metas"){g.className="metas-container";g.innerHTML=metasView(all);const totalPages=Math.max(1,Math.ceil(all.length/8));g.querySelectorAll("[data-meta-page]").forEach(btn=>btn.onclick=()=>{if(btn.dataset.metaPage==="prev")S.metaPage=Math.max(0,S.metaPage-1);else S.metaPage=Math.min(totalPages-1,S.metaPage+1);render()})}else if(v.type==="rhythm"){g.className="rhythm-container";g.innerHTML=ritmoView(all);const totalPages=Math.max(1,Math.ceil(all.length/8));g.querySelectorAll("[data-rhythm-page]").forEach(btn=>btn.onclick=()=>{if(btn.dataset.rhythmPage==="prev")S.rhythmPage=Math.max(0,S.rhythmPage-1);else S.rhythmPage=Math.min(totalPages-1,S.rhythmPage+1);render()})}else if(v.type==="forecast"){g.className="forecast-view";g.innerHTML=forecastTable(all)}else if(v.type==="pending"){g.className="pending-view";g.innerHTML=`<div><strong>${v.tag}</strong><p>${v.message}</p></div>`}else if(v.type==="third"){g.className="stock-area";g.innerHTML=stockSwitch()+`<div class="third-grid">${cards(all)}</div>`;g.querySelectorAll("[data-stock]").forEach(b=>b.onclick=()=>{S.stockView=b.dataset.stock;render()})}else if(v.type==="uf"){g.className="stock-area";g.innerHTML=stockSwitch()+ufTable(all);g.querySelectorAll("[data-stock]").forEach(b=>b.onclick=()=>{S.stockView=b.dataset.stock;render()})}else{g.className="bar-chart";g.innerHTML=rows.map(r=>`<div class="bar-row"><span class="blabel">${r.label}</span><div class="btrack"><div class="bfill" style="width:${r.total/max*100}%">${stack(r,true,total,max)}</div></div><strong>${F.format(r.total)}</strong></div>`).join("")}
 const showSide=v.type!=="pending"&&v.type!=="forecast"&&v.type!=="metas"&&v.type!=="rhythm",grid=document.querySelector(".grid"),aside=grid.querySelector("aside");aside.style.display=showSide?"":"none";grid.classList.toggle("full-view",!showSide);if(!showSide)return;const totals=all.reduce((a,r)=>{["involuntaria","voluntaria","Sem.Info"].forEach(k=>a[k]+=r[k]);a.total+=r.total;return a},{involuntaria:0,voluntaria:0,"Sem.Info":0,total:0});$("tituloComposicao").textContent="Tipo de desconexão";$("composicao").innerHTML=["involuntaria","voluntaria","Sem.Info"].map(k=>`<div class="comp"><span>${k}<b>${F.format(totals[k])}</b></span><div><i style="width:${totals.total?totals[k]/totals.total*100:0}%;background:${CFG.colors[k]}"></i></div></div>`).join("");$("totalVisao").textContent=F.format(totals.total);$("maiorAgente").textContent=all[0]?.label||"—";$("maiorAgenteValor").textContent=F.format(all[0]?.total||0)+" equipamentos"}
function cardDiario(rows,dateField,valueId,subtitleId,labelHoje,labelOntem){const hoje=new Date();hoje.setHours(0,0,0,0);const ontem=new Date(hoje);ontem.setDate(ontem.getDate()-1);const ultima=latest(rows,dateField),valorHoje=sum(rows.filter(r=>same(r[dateField],hoje))),card=$(valueId)?.closest("article"),label=card?.querySelector("span");if(label)label.textContent=labelHoje;if(valorHoje>0){$(valueId).textContent=F.format(valorHoje);$(subtitleId).textContent=show(hoje);return}$(valueId).textContent="0";if(ultima&&+ultima===+ontem){$(subtitleId).textContent=`Ontem · ${show(ontem)}: ${F.format(sum(rows.filter(r=>same(r[dateField],ontem))))}`;return}$(subtitleId).textContent=ultima?`Última movimentação · ${show(ultima)}: ${F.format(sum(rows.filter(r=>same(r[dateField],ultima))))}`:"Sem movimentação registrada"}
function kpis(){const db=latest(S.b,"Data_Baixa"),di=latest(S.i,"Data_Internalizacao"),third=S.e.filter(r=>r.Tipo_Armazem==="TERCEIROS COLETA");cardDiario(S.b,"Data_Baixa","kpiBaixadosHoje","subBaixadosHoje","Baixados hoje","Baixados ontem");$("kpiBaixadosMes").textContent=F.format(sum(S.b.filter(r=>sameMonth(r.Data_Baixa,db))));$("kpiEstoque").textContent=F.format(sum(third));const stockCard=$("kpiEstoque")?.closest("article");if(stockCard){stockCard.querySelector("span").textContent="Estoque D-1 — Terceiras";stockCard.querySelector("small").textContent="Somente terceiros de coleta"}cardDiario(S.i,"Data_Internalizacao","kpiInternalizadosHoje","subInternalizadosHoje","Internalizados hoje","Internalizados ontem");$("kpiInternalizadosMes").textContent=F.format(sum(S.i.filter(r=>sameMonth(r.Data_Internalizacao,di))));$("dataBase").textContent=show([db,di].filter(Boolean).sort((a,b)=>b-a)[0])}
function setView(v){S.view=v;S.left=CFG.rotate;const c=$("contadorVisao"),bar=$("barraVisao");if(c)c.textContent=CFG.rotate+"s";if(bar)bar.style.width="100%";if(v==="estoques")S.stockView="terceiras";if(v==="metas")S.metaPage=0;if(v==="ritmo")S.rhythmPage=0;render()}function timers(){setInterval(()=>$("relogio").textContent=new Date().toLocaleString("pt-BR"),1000);let r=CFG.reload;setInterval(()=>{r--;$("contadorRefresh").textContent=[Math.floor(r/3600),Math.floor(r%3600/60),r%60].map(x=>String(x).padStart(2,"0")).join(":");if(r<=0)location.reload()},1000);setInterval(()=>{S.left--;const c=$("contadorVisao"),bar=$("barraVisao");if(c)c.textContent=Math.max(S.left,0)+"s";if(bar)bar.style.width=`${Math.max(0,Math.min(100,S.left/CFG.rotate*100))}%`;if(S.view==="estoques"&&S.left===15){S.stockView="lojas";render()}if(S.view==="metas"&&S.left===15){S.metaPage=1;render()}if(S.view==="ritmo"&&S.left===15){S.rhythmPage=1;render()}if(S.left<=0)setView(views[(views.indexOf(S.view)+1)%views.length])},1000)}
async function init(){setupResponsiveViewport();setupBrand();setupNav();timers();try{const files=await Promise.all([csv("data/baixados.csv"),csv("data/estoque.csv"),csv("data/internalizados.csv"),csv("data/previsao_entrega.csv"),csv("data/metas_terceiras.csv")]);[S.b,S.e,S.i,S.p,S.m]=files.map(f=>f.rows);const dates=files.map(f=>f.updatedAt).filter(Boolean).sort((a,b)=>b-a);S.dataUpdatedAt=dates[0]||null;kpis();render();startHighlights();$("statusBase").className="status ok";setupHeaderUpdate()}catch(e){$("statusBase").textContent="ERRO NA BASE";$("erroGlobal").hidden=false;$("erroGlobal").textContent=e.message}}init();
